
TEST = u'TEST'
ASSIGNMENT = u'ASSIGNMENT'
HOMEWORK = u'HOMEWORK'
PHASE = u'PHASE'
MEETING = u'MEETING'
LECTURE = u'LECTURE'

TAG_CHOICES = (
    (ASSIGNMENT, ASSIGNMENT),
    (HOMEWORK, HOMEWORK),
    (PHASE, PHASE),
    (MEETING, MEETING),
    (LECTURE, LECTURE),
)